services:
  db:
    image: postgres:16.4
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: no
    ports:
      - 5433:5432
    networks:
      - coucou_chat
    volumes:
      - db_data_volume:/var/lib/postgresql/data

  api:
    container_name: api
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: no
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - coucou_chat

networks:
  coucou_chat:

volumes:
  db_data_volume: